[package]
name = "url_shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
http = "1.2.0"
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
