[package]
name = "url_shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
base62 = "2.2.1"
dotenv = "0.15.0"
hex = "0.4.3"
http = "1.2.0"
rand = "0.8.5"
ring = "0.17.8"
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
