version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_1}:8000"
    environment:
      - API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://localhost:8000/generate_url", \
        "-H", "Content-Type: application/json", \
        "-H", "API-Key: ${API_KEY}", \
        "-d", "{\"url\":\"https://example.com\"}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    sysctls:
      net.core.somaxconn: 65536
      net.ipv4.tcp_max_syn_backlog: 65536

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru --tcp-backlog 65536
    sysctls:
      net.core.somaxconn: 65536
      net.ipv4.tcp_max_syn_backlog: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  # prometheus:
  #   image: "prom/prometheus:latest"
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - backend

  # grafana:
  #   image: "grafana/grafana:latest"
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

volumes:
  redis_data:
    driver: local
