services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "${HOST_PORT_1}:8000"
    environment:
      - API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
        - backend

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  # prometheus:
  #   image: "prom/prometheus:latest"
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - backend


  # grafana:
  #   image: "grafana/grafana:latest"
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"  # Note: Exposed on a different host port to avoid conflict with frontend.
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin  # Change to your preferred password.
  #   depends_on:
  #     - prometheus

volumes:
  redis_data:
