version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1: &backend_template
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_1}:8000"
    environment:
      - API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    sysctls:
      net.core.somaxconn: 65536
      net.ipv4.tcp_max_syn_backlog: 65536
      net.ipv4.tcp_fin_timeout: 30
      net.ipv4.tcp_tw_reuse: 1

  backend2:
    <<: *backend_template
    ports:
      - "${HOST_PORT_2}:8000"

  backend3:
    <<: *backend_template
    ports:
      - "${HOST_PORT_3}:8000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru --tcp-backlog 65536
    sysctls:
      net.core.somaxconn: 65536
      net.ipv4.tcp_max_syn_backlog: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  # prometheus:
  #   image: "prom/prometheus:latest"
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - backend

  # grafana:
  #   image: "grafana/grafana:latest"
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

volumes:
  redis_data:
    driver: local
