name: Docker Compose Quick Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d

      - name: Check frontend
        run: |
          if curl -s http://localhost:3000; then
            echo "✅ Frontend is running"
          else
            echo "❌ Frontend is not running"
            exit 1
          fi

      - name: Teardown
        if: always()
        run: docker-compose down

